#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
 # Source generated colors.
 . "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
  pkill dunst
    dunst \
      -frame_width 1 \
      -lb "${color0}" \
      -nb "${color0}" \
      -cb "${color0}" \
      -bf "${color7}" \
      -cfr "${color3}" \
      -nfr "${color5}" \
      -lfr "${color7}" &
}
reload_dunst
